#!/usr/bin/env bash

pgcontents init -l postgresql://ipbqtgpqdrortr:b5823c62b691904c958ec466758c817e0bb1fcb98e72cb4c72053a0898b82c07@ec2-54-159-22-90.compute-1.amazonaws.com:5432/dct17sg50te6tm --no-prompt

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port 8888 \
	notebooks